/**
 * Astrology Result Source & Precision Copy
 *
 * A typed, content-only dataset of user-facing source, precision, processing,
 * and storage-scope labels for calculated Astrology results:
 * 1. Calculated Chart (`calculated-chart`): Ephemeris math derived from coordinates and time.
 * 2. Optional AI Reflection (`optional-ai-reflection`): Contemplative text synthesized by AI.
 * 3. Date-Only Uncertainty (`date-only-uncertainty`): No supplied time, omitted houses/angles, and lunar uncertainty.
 * 4. Timed-Chart Precision (`timed-chart-precision`): Time-dependent houses, Ascendant, and lunar position.
 * 5. Provider Processing (`provider-processing`): Stateless external computation without user accounts.
 * 6. Local Saved-Copy Scope (`local-saved-scope`): Local device storage isolated completely from dream journals.
 *
 * All wording is strictly provider-neutral, non-predictive, privacy-preserving, and free of guarantees.
 */

export type AstrologyResultSourceId =
  | 'calculated-chart'
  | 'optional-ai-reflection'
  | 'date-only-uncertainty'
  | 'timed-chart-precision'
  | 'provider-processing'
  | 'local-saved-scope';

export type AstrologyResultCategory =
  | 'source'
  | 'precision'
  | 'processing'
  | 'scope';

export interface AstrologyResultSourceItem {
  /** Unique identifier for the source or precision entry */
  id: AstrologyResultSourceId;
  /** Categorical grouping */
  category: AstrologyResultCategory;
  /** Primary display title */
  title: string;
  /** Concise title for compact cards or tab labels */
  shortTitle: string;
  /** Badge label for pill tags or status chips */
  badgeLabel: string;
  /** Single-sentence summary for scannable cards */
  summary: string;
  /** Comprehensive explanatory narrative */
  description: string;
  /** Key bullet points highlighting critical boundaries or distinctions */
  keyTakeaways: readonly string[];
  /** Screen reader accessible description */
  accessibilityLabel: string;
}

export interface AstrologyPrecisionDetail {
  /** Precision identifier */
  id: 'date-only-uncertainty' | 'timed-chart-precision';
  /** Whether exact birth time is incorporated */
  hasExactTime: boolean;
  /** Whether the Ascendant, Midheaven, and houses can be computed */
  hasAscendantAndHouses: boolean;
  /** Short summary of precision level */
  summary: string;
  /** Badge label for status pills */
  badgeLabel: string;
}

export interface AstrologyResultSourceBundle {
  /** Master title for result attribution section */
  title: string;
  /** Subtitle or introductory note */
  subtitle: string;
  /** Master non-predictive disclaimer */
  coreDisclaimer: string;
  /** Map of result source items indexed by id */
  items: Record<AstrologyResultSourceId, AstrologyResultSourceItem>;
  /** Ordered list of item IDs for consistent presentation */
  orderedItemIds: readonly AstrologyResultSourceId[];
}

export const ASTROLOGY_RESULT_SOURCE_ORDERED_IDS: readonly AstrologyResultSourceId[] = [
  'calculated-chart',
  'optional-ai-reflection',
  'date-only-uncertainty',
  'timed-chart-precision',
  'provider-processing',
  'local-saved-scope',
] as const;

export const ASTROLOGY_RESULT_SOURCE_ITEMS: Record<
  AstrologyResultSourceId,
  AstrologyResultSourceItem
> = {
  'calculated-chart': {
    id: 'calculated-chart',
    category: 'source',
    title: 'Astronomical Ephemeris Calculation',
    shortTitle: 'Calculated Chart',
    badgeLabel: 'Calculated',
    summary:
      'Planetary positions and geometric aspects are computed using deterministic astronomical ephemeris models.',
    description:
      'The celestial coordinates and aspect angles in your chart are calculated strictly through astronomical algorithms based on your birth date, time, and geographic coordinates. This represents the geometric configuration of the sky at that moment and does not use artificial intelligence, subjective interpretation, or predictive fortune-telling.',
    keyTakeaways: [
      'Planetary coordinates are calculated through deterministic astronomical ephemeris formulas.',
      'Derived directly from observer coordinates and timestamp without generative AI synthesis.',
      'Provides calculated geometric positions for introspective inquiry rather than deterministic life outcomes.',
    ],
    accessibilityLabel:
      'Source attribution confirming planetary positions are mathematically calculated with astronomical ephemeris algorithms.',
  },

  'optional-ai-reflection': {
    id: 'optional-ai-reflection',
    category: 'source',
    title: 'Optional AI Reflection',
    shortTitle: 'AI Reflection',
    badgeLabel: 'AI Reflection',
    summary:
      'Written reflections are generated by an artificial intelligence model as open-ended prompts for personal contemplation.',
    description:
      'When you choose to generate a written reflection, an artificial intelligence language model synthesizes symbolic themes based on your calculated placements. These insights are intended as open-ended metaphors for personal journaling and self-reflection. The reflection is completely separate from the mathematical calculation and does not predict future events or offer medical or psychological diagnosis.',
    keyTakeaways: [
      'Written commentary is produced by a generative artificial intelligence language model.',
      'Completely distinct and independent from the underlying ephemeris mathematical calculation.',
      'Designed exclusively for personal introspection and contemplative inquiry; never diagnostic or predictive.',
    ],
    accessibilityLabel:
      'Source attribution stating that interpretive commentary is generated by an artificial intelligence model for personal contemplation.',
  },

  'date-only-uncertainty': {
    id: 'date-only-uncertainty',
    category: 'precision',
    title: 'Date-Only Uncertainty',
    shortTitle: 'Date Only',
    badgeLabel: 'Date-Only',
    summary:
      'Calculations without a birth time omit the Ascendant, Midheaven, and houses; lunar and degree positions should be read with the supplied uncertainty notes.',
    description:
      'When birth time is omitted, the calculation request contains the birth date with no time value. Because the Ascendant, Midheaven, and twelve astrological houses depend on clock time and local horizon geometry, they are omitted. Read lunar and degree positions alongside the uncertainty notes returned with the chart.',
    keyTakeaways: [
      'The calculation request sends no birth-time value.',
      'Ascendant, Midheaven, and house cusps are omitted because they require precise birth time.',
      'Lunar and degree positions should be read alongside the chart’s uncertainty notes.',
    ],
    accessibilityLabel:
      'Precision notice explaining date-only chart calculations omit Ascendant and houses and carry lunar variance.',
  },

  'timed-chart-precision': {
    id: 'timed-chart-precision',
    category: 'precision',
    title: 'Timed Chart Precision',
    shortTitle: 'Exact Time',
    badgeLabel: 'Timed Precision',
    summary:
      'Providing a birth time allows calculation of time-dependent angles, houses, and lunar position.',
    description:
      'Including a clock time (hour and minute) along with coordinates enables calculation of horizon and meridian angles such as the Ascendant and Midheaven, plus house placement. These calculated details remain symbolic material for reflection and are only as accurate as the information supplied.',
    keyTakeaways: [
      'Computes the Ascendant, Midheaven, and all twelve house cusps based on verified clock time.',
      'Calculates lunar placement for the supplied time rather than date-only mode.',
      'Offers additional geometric detail while maintaining an open-ended, non-predictive perspective.',
    ],
    accessibilityLabel:
      'Precision notice describing timed chart calculations including Ascendant, houses, and precise lunar coordinates.',
  },

  'provider-processing': {
    id: 'provider-processing',
    category: 'processing',
    title: 'External Provider Processing',
    shortTitle: 'Provider Processing',
    badgeLabel: 'External Processing',
    summary:
      'Calculations and optional reflections are processed through separate external services without creating an app account.',
    description:
      'Astronomical calculations and optional AI reflections are performed through server endpoints. Chart requests contain the calculation fields disclosed before submission; optional reflection requests contain a capped chart summary instead of birth details. No app account is required, but external services may retain operational records under their own terms.',
    keyTakeaways: [
      'Processed through secure external server endpoints for mathematical computation and reflection synthesis.',
      'No app account, personal name, or email address is included in these request contracts.',
      'External services may retain operational records under their independent privacy terms.',
    ],
    accessibilityLabel:
      'Processing disclosure explaining stateless external calculation without account creation or identity linkage.',
  },

  'local-saved-scope': {
    id: 'local-saved-scope',
    category: 'scope',
    title: 'Local Device Storage Scope',
    shortTitle: 'Saved on Device',
    badgeLabel: 'Saved on Device',
    summary:
      'Profiles, charts, and reflections are saved exclusively in local device storage and are completely separated from dream journals.',
    description:
      'Your birth profile, calculated placements, and generated reflections reside exclusively in local storage on this device. They are never synced to a remote cloud database or merged with Jungian dream entries. Deleting your astrology profile from the device clears all saved astrological data locally, while your dream entries remain entirely unaffected.',
    keyTakeaways: [
      'All saved profiles, charts, and reflections are stored strictly on-device.',
      'Strict isolation prevents astrology data from mixing with Jungian dream journals.',
      'Local deletion permanently removes all saved astrological records from the device.',
    ],
    accessibilityLabel:
      'Storage scope disclosure confirming all astrology records are saved locally and kept isolated from dream entries.',
  },
};

export const ASTROLOGY_PRECISION_DETAILS: Record<
  'date-only-uncertainty' | 'timed-chart-precision',
  AstrologyPrecisionDetail
> = {
  'date-only-uncertainty': {
    id: 'date-only-uncertainty',
    hasExactTime: false,
    hasAscendantAndHouses: false,
    summary:
      'Date-only chart without Ascendant, Midheaven, or houses; read positions with the supplied uncertainty notes.',
    badgeLabel: 'Date-Only',
  },
  'timed-chart-precision': {
    id: 'timed-chart-precision',
    hasExactTime: true,
    hasAscendantAndHouses: true,
    summary:
      'Timed chart including time-dependent angles and house placement, subject to the accuracy of supplied inputs.',
    badgeLabel: 'Timed Precision',
  },
};

export const ASTROLOGY_RESULT_SOURCE_BUNDLE: AstrologyResultSourceBundle = {
  title: 'Astrology Sources & Precision',
  subtitle:
    'Transparent disclosures on calculation mechanics, precision levels, external processing, and device storage.',
  coreDisclaimer:
    'Astrological placements and reflections are offered for symbolic contemplation and creative inquiry. They are not predictive of future events, scientifically factual, or a substitute for medical or psychological guidance.',
  items: ASTROLOGY_RESULT_SOURCE_ITEMS,
  orderedItemIds: ASTROLOGY_RESULT_SOURCE_ORDERED_IDS,
};

/**
 * Retrieve a specific result source or precision copy item by its identifier.
 */
export function getAstrologyResultSourceItem(
  id: AstrologyResultSourceId,
): AstrologyResultSourceItem {
  return ASTROLOGY_RESULT_SOURCE_ITEMS[id];
}

/**
 * Retrieve all result source and precision items in recommended display order.
 */
export function getAllAstrologyResultSourceItems(): AstrologyResultSourceItem[] {
  return ASTROLOGY_RESULT_SOURCE_ORDERED_IDS.map(
    (id) => ASTROLOGY_RESULT_SOURCE_ITEMS[id],
  );
}

/**
 * Retrieve result source items filtered by categorical grouping.
 */
export function getAstrologyResultSourceItemsByCategory(
  category: AstrologyResultCategory,
): AstrologyResultSourceItem[] {
  return ASTROLOGY_RESULT_SOURCE_ORDERED_IDS
    .map((id) => ASTROLOGY_RESULT_SOURCE_ITEMS[id])
    .filter((item) => item.category === category);
}

/**
 * Retrieve the full result source and precision bundle.
 */
export function getAstrologyResultSourceBundle(): AstrologyResultSourceBundle {
  return ASTROLOGY_RESULT_SOURCE_BUNDLE;
}

/**
 * Retrieve the badge label for a specific result source or precision item.
 */
export function getResultSourceBadgeLabel(id: AstrologyResultSourceId): string {
  return ASTROLOGY_RESULT_SOURCE_ITEMS[id].badgeLabel;
}

/**
 * Retrieve the appropriate precision copy item based on whether birth time was provided.
 */
export function getPrecisionCopyForTime(
  hasBirthTime: boolean,
): AstrologyResultSourceItem {
  return hasBirthTime
    ? ASTROLOGY_RESULT_SOURCE_ITEMS['timed-chart-precision']
    : ASTROLOGY_RESULT_SOURCE_ITEMS['date-only-uncertainty'];
}

/**
 * Retrieve structured precision details based on whether birth time was provided.
 */
export function getPrecisionDetailForTime(
  hasBirthTime: boolean,
): AstrologyPrecisionDetail {
  return hasBirthTime
    ? ASTROLOGY_PRECISION_DETAILS['timed-chart-precision']
    : ASTROLOGY_PRECISION_DETAILS['date-only-uncertainty'];
}

/**
 * Retrieve copy describing the mathematical calculation source.
 */
export function getCalculatedChartSourceCopy(): AstrologyResultSourceItem {
  return ASTROLOGY_RESULT_SOURCE_ITEMS['calculated-chart'];
}

/**
 * Retrieve copy describing the optional AI reflection source.
 */
export function getAiReflectionSourceCopy(): AstrologyResultSourceItem {
  return ASTROLOGY_RESULT_SOURCE_ITEMS['optional-ai-reflection'];
}

/**
 * Retrieve copy describing the local storage scope and dream isolation.
 */
export function getLocalSavedScopeCopy(): AstrologyResultSourceItem {
  return ASTROLOGY_RESULT_SOURCE_ITEMS['local-saved-scope'];
}

/**
 * Retrieve copy describing the external provider processing boundary.
 */
export function getProviderProcessingCopy(): AstrologyResultSourceItem {
  return ASTROLOGY_RESULT_SOURCE_ITEMS['provider-processing'];
}

/**
 * Type guard verifying whether a value is a recognized AstrologyResultSourceId.
 */
export function isRecognizedResultSourceId(
  value: unknown,
): value is AstrologyResultSourceId {
  return (
    typeof value === 'string' &&
    ASTROLOGY_RESULT_SOURCE_ORDERED_IDS.includes(
      value as AstrologyResultSourceId,
    )
  );
}
